image: docker.diconium.com:443/diconium/hub/mirror/node:14.18.1

# job that deploys gitlab pages
pages:
  pages:
   stage: deploy
   script:
     - npm install
     - npm run build
   artifacts:
     paths:
       - public
   only:
     - master
 